# Generated by Django 4.1 on 2023-04-24 04:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disable', 'Disable')], default='active', max_length=20)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent_menu', mptt.fields.TreeForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.menu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disable', 'Disable')], default='active', max_length=20)),
                ('product_price', models.CharField(max_length=20)),
                ('product_image', models.ImageField(max_length=50, upload_to='products')),
                ('short_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('long_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('featured_product', models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=10, null=True)),
                ('popular_product', models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=10, null=True)),
                ('parent_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menu')),
            ],
        ),
    ]
