# Generated by Django 4.1.7 on 2023-04-21 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.menu'),
        ),
    ]
