# Generated by Django 4.1.7 on 2023-04-21 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_menu_parent_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disable', 'Disable')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disable', 'Disable')], default='active', max_length=20)),
                ('product_price', models.CharField(max_length=20)),
                ('sale_price', models.CharField(blank=True, max_length=20, null=True)),
                ('product_image', models.ImageField(max_length=50, upload_to='products')),
                ('parent_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menu')),
            ],
        ),
    ]
