# Generated by Django 4.1.7 on 2023-04-22 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_menu_parent_menu_alter_menu_status_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_image',
            field=models.ImageField(default=django.utils.timezone.now, max_length=55, upload_to='menus'),
            preserve_default=False,
        ),
    ]
