# Generated by Django 4.1.7 on 2023-04-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_menu_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_image',
        ),
    ]
