# Generated by Django 4.1.7 on 2023-04-22 11:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
