# Generated by Django 4.1.7 on 2023-04-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_product',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='popular_product',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=10, null=True),
        ),
    ]
